# Generated by Django 3.1.3 on 2020-11-13 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Communication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_text', models.TextField(verbose_name='Текст дз')),
                ('expire', models.DateTimeField(verbose_name='Дедлайн')),
            ],
            options={
                'verbose_name': 'Домашнее задание по ОДК',
                'verbose_name_plural': 'Домашние задания по ОДК',
            },
        ),
        migrations.CreateModel(
            name='ComputerPractice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_text', models.TextField(verbose_name='Текст дз')),
                ('expire', models.DateTimeField(verbose_name='Дедлайн')),
            ],
            options={
                'verbose_name': 'Домашнее задание по КП',
                'verbose_name_plural': 'Домашние задания по КП',
            },
        ),
        migrations.CreateModel(
            name='Economics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_text', models.TextField(verbose_name='Текст дз')),
                ('expire', models.DateTimeField(verbose_name='Дедлайн')),
            ],
            options={
                'verbose_name': 'Домашнее задание по экономике',
                'verbose_name_plural': 'Домашние задания по экономике',
            },
        ),
        migrations.CreateModel(
            name='IT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_text', models.TextField(verbose_name='Текст дз')),
                ('expire', models.DateTimeField(verbose_name='Дедлайн')),
            ],
            options={
                'verbose_name': 'Домашнее задание по ИТВПД',
                'verbose_name_plural': 'Домашние задания по ИТВПД',
            },
        ),
        migrations.CreateModel(
            name='Management',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_text', models.TextField(verbose_name='Текст дз')),
                ('expire', models.DateTimeField(verbose_name='Дедлайн')),
            ],
            options={
                'verbose_name': 'Домашнее задание по менеджменту',
                'verbose_name_plural': 'Домашние задания по менеджменту',
            },
        ),
    ]
