# Generated by Django 3.1.3 on 2020-11-13 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0003_remove_economics_expire'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='it',
            name='expire',
        ),
    ]
