# Generated by Django 3.1.3 on 2020-11-14 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0005_auto_20201115_0005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='expire',
        ),
    ]
